services:
  eurekaserver:
    image: "aravind4799/eurekaserver:v3"
    container_name: "eurekaserver-ms-container"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_interval: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    ports:
      - "8070:8070"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  configserver:
    image: "aravind4799/configserver:v3"
    container_name: "configserver-ms-container"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_interval: 10s
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "aravind4799/accounts:v3"
    container_name: "accounts-ms-container"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans:
    image: "aravind4799/loans:v3"
    container_name: "loans-ms-container"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  cards:
    image: "aravind4799/cards:v3"
    container_name: "cards-ms-container"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

networks:
  ms-network:
    driver: "bridge"




