build:
  version: "v1"

accounts:
  message: "accounts related prod APIs "
  contactDetails:
    name: "aravind - Product Owner"
    email: "aravind@in.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384