build:
  version: "2.0"

cards:
  message: "Welcome to  cards related qa APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@in.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721