build:
  version: "5.0"

cards:
  message: "Welcome to  cards related prod Rest ApIs"
  contactDetails:
    name: "Arya Stark"
    email: "aryaStark@in.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721