build:
  version: "2.0"

loans:
  message: "Welcome to  loans related qa APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@ince.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956