services:

  accountsdb:
    image: mysql
    container_name: "accountsdb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "accountsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    image: mysql
    container_name: "loansdb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "loansdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mysql
    container_name: "cardsdb"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "cardsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: "rabbitmq:3.12-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_interval: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "aravind4799/configserver:v2"
    container_name: "configserver-ms-container"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_interval: 10s
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "aravind4799/accounts:v2"
    container_name: "accounts-ms-container"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"

    depends_on:
      accountsdb:
        condition: service_healthy

    extends:
      file: common-config.yml
      service: micorservice-configserver-config

  loans:
    image: "aravind4799/loans:v2"
    container_name: "loans-ms-container"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: micorservice-configserver-config

  cards:
    image: "aravind4799/cards:v2"
    container_name: "cards-ms-container"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: micorservice-configserver-config

networks:
  ms-network:
    driver: "bridge"