server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
#    active: native
     active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#           search-locations: "file:///C://config/"
        git:
          uri: "https://github.com/aravind4799/Config.git"
          default-label: "main"
          timeout: 5000
          clone-on-start: true
          force-pull: true
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


encrypt:
  key: "6B4332AF6CEF623621732991B6431"